---
config:
  theme: neo-dark
title: Package m3acnl.game.affichage
---

classDiagram
direction TB
    class PartieAffichage {
	    - partie : Partie
        - labelTemps : Label
        - boutons : Button[][]
        - gridPane : GridPane
        - SUPERPOSITION_RATIO : double
        - backgroundPane : StackPane
        - derniereTaille : double
        - timeline : Timeline
        - ajoue : boolean
        - niveauAide : int
        - elementAide : ElementAide
        - numeroAide : int
        - aideVoisin : AideVoisin
        - genererMenu : GenererAsset
        - primaryStage : Stage
        - mainScene : Scene 
        + PartieAffichage(difficulte : Difficulte)
        + *@override* start(prim : Stage) : void
        - creerBackground() : void
        - creerPanneauDeControle() : VBox
        - initialiserBoutons() : void
        - creerPanneauAide() : VBox
        - actualiserAffichage() : void
        - actualiserLabelTemps() : void
        - ajusterTailleImages() : void
        - previsualiserEtat(event : MouseEvent, x : int, y : int) : void
        - restaurerEtat(x : int, y : int) : void
        - ajusterTailleBoutons(boutons : Button[][]) : void
        - victoire() : void
        - afficherOverlayVictoire() : void
        - cacherOverlay(mainLayout : BorderPane) : void
        - actualiserAideLabel() : void
        - surbrillanceAide() : void
        - getResourceElementJeu(i : int, j : int) : String
        - activerAide() : void
        - activerElement(event : MouseEvent, x : int, y : int) : void
        - trouverNoeudLePlusProche(doubleLien : DoubleLien, event : MouseEvent) : Noeud
        - pause() : void
        - demarrerChrono() : void
        - relancerPartie(mainLayout : BorderPane) : void
        - retour() : void
        - avancer() : void
        - check() : void
        - sauvegarde() : void
        - retourSauvegarde() : void


    }

